{"uuid": "903580fb-25ed-418c-b2d9-e83dc78a5f08", "children": ["31f3285f-28ac-44f8-81dd-554602c164c5"], "befores": [{"name": "browser", "status": "passed", "start": 1634364185309, "stop": 1634364192574}], "afters": [{"name": "browser::final", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Session timed out or not found\n\n", "trace": "  File \"/home/pavel/qa/selenium_logs/venv/lib/python3.8/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/pavel/qa/selenium_logs/conftest.py\", line 80, in final\n    driver.quit()\n  File \"/home/pavel/qa/selenium_logs/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 698, in quit\n    self.execute(Command.QUIT)\n  File \"/home/pavel/qa/selenium_logs/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/home/pavel/qa/selenium_logs/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1634364355287, "stop": 1634364355328}], "start": 1634364185309, "stop": 1634364355328}