{"uuid": "8570fdf9-8f4a-4d4e-bb49-f0741c1d135a", "children": ["ce6310ff-7ee5-4d39-8de5-c3da9376ff6d"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Requested environment is not available\n\n", "trace": "  File \"/home/pbochkarev/sources/selenium_logs/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/pbochkarev/sources/selenium_logs/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/pbochkarev/sources/selenium_logs/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/pbochkarev/sources/selenium_logs/conftest.py\", line 58, in browser\n    driver = webdriver.Remote(command_executor=f\"http://{executor}:4444/wd/hub\",\n  File \"/home/pbochkarev/sources/selenium_logs/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/pbochkarev/sources/selenium_logs/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/home/pbochkarev/sources/selenium_logs/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/home/pbochkarev/sources/selenium_logs/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1637778068241, "stop": 1637778068275}], "start": 1637778068241, "stop": 1637778068367}