{"uuid": "4202895b-2472-4820-8003-b34e3e89fef9", "children": ["696736d1-674b-45a9-a722-693745ba0e96"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"/home/pbochkarev/sources/selenium_logs/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/pbochkarev/sources/selenium_logs/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/pbochkarev/sources/selenium_logs/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/pbochkarev/sources/selenium_logs/conftest.py\", line 47, in browser\n    driver = webdriver.Chrome(executable_path=f\"{DRIVERS}/chromedriver\",\n  File \"/home/pbochkarev/sources/selenium_logs/venv/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"/home/pbochkarev/sources/selenium_logs/venv/lib/python3.8/site-packages/selenium/webdriver/common/service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1637777674366, "stop": 1637777674371}], "start": 1637777674366, "stop": 1637777674557}